{{/*
#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: params-{{ template "ita-by-ansible-execute.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ita-by-ansible-execute.labels" . | nindent 4 }}
data: {{ toYaml .Values.extraEnv | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-agent-create
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ita-by-ansible-execute.labels" . | nindent 4 }}
data: 
    k8s_pod.yml: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: ita-by-ansible-agent-{{`{{ unique_name }}`}}
      spec:
        containers:
        - name: ita-by-ansible-agent
          image: "{{`{{ ansible_agent_image }}`}}"
          command: [
            "bash",
            "-c",
            "{{`{{ str_shell_command }}`}}",
          ]
          env:
          {{ range $name, $value := .Values.extraEnv -}}
          - name: {{ $name }}
            value: "{{ $value }}"
          {{ end -}}
          - name: EXEC_DIR
            value: {{`{{ container_mount_path_driver }}`}}
          volumeMounts:
          - name: volume-subpath
            mountPath: {{`{{ container_mount_path_driver }}`}}
            subPath: {{`{{ host_mount_path_driver }}`}}
          - name: volume-subpath
            mountPath: {{`{{ container_mount_path_conductor }}`}}
            subPath: {{`{{ host_mount_path_conductor }}`}}
        volumes:
        - name: volume-subpath
          persistentVolumeClaim:
            claimName: pvc-{{ .Values.global.itaGlobalDefinition.name }}
        restartPolicy: Never
